/**
 * Canonical Mapping between stable internal achievement IDs and Google Play Games achievement IDs.
 * 
 * Internal IDs are canonical and permanent. Google Play achievement IDs (opaque alphanumeric strings)
 * are generated by Google Play Console when achievements are created.
 */
export interface PlayAchievementMapping {
  readonly internalId: string;
  readonly playGamesId: string;
  readonly isIncremental?: boolean;
  readonly totalSteps?: number;
}

export const PLAY_ACHIEVEMENT_MAPPINGS: Record<string, PlayAchievementMapping> = {
  'war.first_casualty': standard('war.first_casualty', 'CgkIz5juh94JEAIQDA'),
  'war.first_battle': standard('war.first_battle', 'CgkIz5juh94JEAIQEQ'),
  'war.first_win': standard('war.first_win', 'CgkIz5juh94JEAIQEg'),
  'war.first_defeat': standard('war.first_defeat', 'CgkIz5juh94JEAIQEw'),
  'war.first_rescue': standard('war.first_rescue', 'CgkIz5juh94JEAIQDQ'),
  'war.first_battle_win': standard('war.first_battle_win', 'CgkIz5juh94JEAIQCw'),
  'war.assassin': standard('war.assassin', 'CgkIz5juh94JEAIQAg'),
  'war.not_today': standard('war.not_today', 'CgkIz5juh94JEAIQBQ'),
  'war.battle_layer_3': standard('war.battle_layer_3', 'CgkIz5juh94JEAIQBg'),
  'war.battle_layer_4': standard('war.battle_layer_4', 'CgkIz5juh94JEAIQCA'),
  'war.deep_battle_win': standard('war.deep_battle_win', 'CgkIz5juh94JEAIQAA'),
  'war.royal_disaster': standard('war.royal_disaster', 'CgkIz5juh94JEAIQCQ'),
  'war.massacre': standard('war.massacre', 'CgkIz5juh94JEAIQFA'),
  'war.juggernaut': standard('war.juggernaut', 'CgkIz5juh94JEAIQGA'),
  'war.expert_strategist': standard('war.expert_strategist', 'CgkIz5juh94JEAIQGg'),
  'war.poor_strategy': standard('war.poor_strategy', 'CgkIz5juh94JEAIQGw'),
  'war.grave_intelligence': standard('war.grave_intelligence', 'CgkIz5juh94JEAIQGQ'),
  'war.cavalry_came': standard('war.cavalry_came', 'CgkIz5juh94JEAIQFw'),
  'war.no_reinforcements_win': standard('war.no_reinforcements_win', 'CgkIz5juh94JEAIQFQ'),
  'war.five_battles_game': standard('war.five_battles_game', 'CgkIz5juh94JEAIQBw'),
  'war.pyrrhic_victory': standard('war.pyrrhic_victory', 'CgkIz5juh94JEAIQBA'),
  'war.untouchable': standard('war.untouchable', 'CgkIz5juh94JEAIQCg'),
  'war.comeback_15': standard('war.comeback_15', 'CgkIz5juh94JEAIQDg'),
  'war.marathon': standard('war.marathon', 'CgkIz5juh94JEAIQDw'),
  'profile.campaigner': standard('profile.campaigner', 'CgkIz5juh94JEAIQAQ'),
  'profile.veteran': incremental('profile.veteran', 'CgkIz5juh94JEAIQEA', 25),
  'profile.centurion': incremental('profile.centurion', 'CgkIz5juh94JEAIQAw', 100)
};

function standard(internalId: string, playGamesId: string): PlayAchievementMapping {
  return { internalId, playGamesId, isIncremental: false };
}

function incremental(
  internalId: string,
  playGamesId: string,
  totalSteps: number
): PlayAchievementMapping {
  return { internalId, playGamesId, isIncremental: true, totalSteps };
}
