/**
 * Canonical Mapping between stable internal achievement IDs and Google Play Games achievement IDs.
 * 
 * Internal IDs are canonical and permanent. Google Play achievement IDs (opaque alphanumeric strings)
 * are generated by Google Play Console when achievements are created.
 */
export interface PlayAchievementMapping {
  readonly internalId: string;
  readonly playGamesId: string;
  readonly isIncremental?: boolean;
  readonly totalSteps?: number;
}

export const PLAY_ACHIEVEMENT_MAPPINGS: Record<string, PlayAchievementMapping> = {
  'war.assassin': {
    internalId: 'war.assassin',
    playGamesId: 'CgkI_PLACEHOLDER_ASSASSIN',
    isIncremental: false
  },
  'war.pyrrhic_victory': {
    internalId: 'war.pyrrhic_victory',
    playGamesId: 'CgkI_PLACEHOLDER_PYRRHIC_VICTORY',
    isIncremental: false
  },
  'war.massacre': {
    internalId: 'war.massacre',
    playGamesId: 'CgkI_PLACEHOLDER_MASSACRE',
    isIncremental: false
  },
  'war.battle_layer_3': {
    internalId: 'war.battle_layer_3',
    playGamesId: 'CgkI_PLACEHOLDER_BATTLE_LAYER_3',
    isIncremental: false
  },
  'war.battle_layer_4': {
    internalId: 'war.battle_layer_4',
    playGamesId: 'CgkI_PLACEHOLDER_BATTLE_LAYER_4',
    isIncremental: false
  },
  'war.not_today': {
    internalId: 'war.not_today',
    playGamesId: 'CgkI_PLACEHOLDER_NOT_TODAY',
    isIncremental: false
  },
  'war.royal_disaster': {
    internalId: 'war.royal_disaster',
    playGamesId: 'CgkI_PLACEHOLDER_ROYAL_DISASTER',
    isIncremental: false
  },
  'war.untouchable': {
    internalId: 'war.untouchable',
    playGamesId: 'CgkI_PLACEHOLDER_UNTOUCHABLE',
    isIncremental: false
  },
  'war.marathon': {
    internalId: 'war.marathon',
    playGamesId: 'CgkI_PLACEHOLDER_MARATHON',
    isIncremental: false
  },
  'war.comeback_15': {
    internalId: 'war.comeback_15',
    playGamesId: 'CgkI_PLACEHOLDER_COMEBACK_15',
    isIncremental: false
  },
  'profile.veteran': {
    internalId: 'profile.veteran',
    playGamesId: 'CgkI_PLACEHOLDER_VETERAN',
    isIncremental: true,
    totalSteps: 25
  },
  'profile.centurion': {
    internalId: 'profile.centurion',
    playGamesId: 'CgkI_PLACEHOLDER_CENTURION',
    isIncremental: true,
    totalSteps: 100
  }
};
