import {
  AuthoredDialogueRecord,
  CommanderDossierRecord,
  NarrativeTransitionRecord
} from '../core/models/narrative.model';

export const CHAPTER_ONE_DIALOGUE: readonly AuthoredDialogueRecord[] = [
  { id: 'C1W1-MAR-01', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'introduction', text: 'At Mont-Rouge, monsieur, we placed two ancient traditions at one table. Only one of them arrived with the dignity to remain seated.', availability: 'first_play', revealIds: ['R01', 'R05'] },
  { id: 'C1W1-MAR-02', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'context', text: 'The French Witness Wheel opened as promised. The Swiss wheel opened eyes it was never asked to possess. Matthias then closed the Accord.', availability: 'first_play', revealIds: ['R02', 'R06', 'R07', 'R08', 'R09'] },
  { id: 'C1W1-MAR-03', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'special_clash', text: 'A card without pedigree fells an Ace. Barbaric. Lawful. I dislike it twice.', availability: 'replay' },
  { id: 'C1W1-MAR-04', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'narrow_clash', text: 'One rank: the difference between serviceable and served with apologies.', availability: 'any' },
  { id: 'C1W1-MAR-05', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'rescue', text: 'There. Proper stock returns to the cellar.', availability: 'any' },
  { id: 'C1W1-MAR-06', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'failed_rescue', text: 'Two vintages spent to preserve neither. An undisciplined finish.', availability: 'any' },
  { id: 'C1W1-MAR-07', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'battle_ace_lost', text: 'An Ace matured for this command and discarded in an instant. Mont-Rouge had more ceremony.', availability: 'replay' },
  { id: 'C1W1-MAR-08', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'battle_two_lost', text: 'Do not mock the little rank. Its absence leaves a very large hole.', availability: 'any' },
  { id: 'C1W1-MAR-09', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'deep_battle', text: 'Layer upon layer. Even a rind knows when thickness has become stubbornness.', availability: 'any' },
  { id: 'C1W1-MAR-10', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'large_battle_loss', text: 'A whole shelf gone. Matthias would count the crumbs and call the loss precise.', availability: 'replay', revealIds: ['R03'] },
  { id: 'C1W1-MAR-11', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'concession', text: 'Non. That card is young stock. We do not spend a cellar to rescue a curd.', availability: 'any' },
  { id: 'C1W1-MAR-12', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'desperate_rescue', text: 'Open the last shelf. Preservation without survival is merely inventory.', availability: 'any' },
  { id: 'C1W1-MAR-13', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'contextual', text: 'He would object that the wheel was six minutes too warm. He always mistakes a correction for a personality.', availability: 'replay', revealIds: ['R03', 'R04'] },
  { id: 'C1W1-MAR-14', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'contextual', text: 'I had his word. Whatever else the Swiss preserve, they did not preserve that.', availability: 'first_play', revealIds: ['R04'] },
  { id: 'C1W1-MAR-15', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'result', text: 'The cards have rendered a verdict. Naturally, history will appeal.', availability: 'any' },
  { id: 'C1W1-MAR-16', commanderId: 'quartermaster', mode: 'standard', warIndex: 1, event: 'resolution', text: 'When the wheel opened, Matthias asked me to wait. That was the hour I had expected him to stand beside me.', availability: 'first_play', revealIds: ['R04', 'R08', 'R09'] },

  { id: 'C1W2-MAT-01', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'introduction', text: 'Correction one: the Swiss wheel never left Swiss custody. Correction two: this made the result more alarming, not less.', availability: 'first_play', revealIds: ['R07', 'R08'] },
  { id: 'C1W2-MAT-02', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'context', text: 'I suspended ratification pending inquiry. Marcel proceeded before the ink on my request had dried.', availability: 'first_play', revealIds: ['R08', 'R11', 'R12'] },
  { id: 'C1W2-MAT-03', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'special_clash', text: 'The exception is documented. My irritation does not amend it.', availability: 'replay' },
  { id: 'C1W2-MAT-04', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'narrow_clash', text: 'One rank. A small interval remains an interval.', availability: 'any' },
  { id: 'C1W2-MAT-05', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'rescue', text: 'The candidate resolved above threshold. Acceptable.', availability: 'any' },
  { id: 'C1W2-MAT-06', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'failed_rescue', text: 'Result outside expectation. Not outside possibility.', availability: 'any' },
  { id: 'C1W2-MAT-07', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'battle_ace_lost', text: 'Ace removed. Fourteen points of public certainty become one casualty.', availability: 'replay' },
  { id: 'C1W2-MAT-08', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'battle_two_lost', text: 'Specialist removed. Update every Ace accordingly.', availability: 'any' },
  { id: 'C1W2-MAT-09', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'deep_battle', text: 'Third layer. Rare is not the same word as impossible.', availability: 'any' },
  { id: 'C1W2-MAT-10', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'large_battle_loss', text: 'Nine cards. Marcel will call that a cellar; it remains nine cards.', availability: 'replay', revealIds: ['R03'] },
  { id: 'C1W2-MAT-11', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'concession', text: 'Negative expectation. Pride is not a reserve card.', availability: 'any' },
  { id: 'C1W2-MAT-12', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'desperate_rescue', text: 'Critical threshold. The model changes because the position changed.', availability: 'any' },
  { id: 'C1W2-MAT-13', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'contextual', text: 'Marcel rests a wheel at eleven degrees and an argument at boiling. I have measured both.', availability: 'replay', revealIds: ['R03', 'R04'] },
  { id: 'C1W2-MAT-14', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'contextual', text: 'Procedure is not betrayal. Proceeding without your counterpart is closer to the definition.', availability: 'first_play', revealIds: ['R08', 'R11', 'R12'] },
  { id: 'C1W2-MAT-15', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'result', text: 'One War is a sample, not a conclusion. Record it anyway.', availability: 'any' },
  { id: 'C1W2-MAT-16', commanderId: 'analyst', mode: 'standard', warIndex: 2, event: 'resolution', text: 'Marcel used the framework we wrote together while I was asking why its witness had become impossible. Tell me which act looks like abandonment.', availability: 'first_play', revealIds: ['R05', 'R07', 'R08', 'R11', 'R12'] },

  { id: 'C1W3-BAS-01', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'introduction', text: 'The blind wheel opened seven eyes. Four men closed eight.', availability: 'first_play', revealIds: ['R31'] },
  { id: 'C1W3-BAS-02', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'context', text: 'Both accounts are honest. This is why neither can be trusted alone.', availability: 'first_play', revealIds: ['R32', 'R35'] },
  { id: 'C1W3-BAS-03', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'special_clash', text: 'The smallest soldier bows to no crown. Today the table remembers.', availability: 'replay', revealIds: ['R33'] },
  { id: 'C1W3-BAS-04', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'narrow_clash', text: 'A single step separates supper from hunger. Ask the winter.', availability: 'any' },
  { id: 'C1W3-BAS-05', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'rescue', text: 'Tomorrow arrived early and brought another card.', availability: 'any' },
  { id: 'C1W3-BAS-06', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'failed_rescue', text: 'The curd accepted the offering. The line did not.', availability: 'any' },
  { id: 'C1W3-BAS-07', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'battle_ace_lost', text: 'A great head falls. Somewhere, a very small guest remains uninvited.', availability: 'first_play', revealIds: ['R33'] },
  { id: 'C1W3-BAS-08', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'battle_two_lost', text: 'The humble card has finished its enormous appointment.', availability: 'any' },
  { id: 'C1W3-BAS-09', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'deep_battle', text: 'Cave beneath cave. At the bottom, breath is waiting for warmth.', availability: 'first_play', revealIds: ['R36'] },
  { id: 'C1W3-BAS-10', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'large_battle_loss', text: 'A meadow entered the cellar grain by grain. No cow followed. Armies did.', availability: 'first_play', revealIds: ['R34'] },
  { id: 'C1W3-BAS-11', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'concession', text: 'Let the card go. The War is longer than its shadow.', availability: 'any' },
  { id: 'C1W3-BAS-12', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'desperate_rescue', text: 'The last rind is also a door. Open it.', availability: 'any' },
  { id: 'C1W3-BAS-13', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'contextual', text: 'The precise man calls me inadmissible. The fragrant man calls me unbearable. Both spell my name correctly.', availability: 'replay' },
  { id: 'C1W3-BAS-14', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'contextual', text: 'One friend says wait. One friend says now. The curd hears only drums.', availability: 'first_play' },
  { id: 'C1W3-BAS-15', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'result', text: 'Victory, defeat—two names written on the rind before it is cut.', availability: 'any' },
  { id: 'C1W3-BAS-16', commanderId: 'attritionist', mode: 'standard', warIndex: 3, event: 'resolution', text: 'Two honest men will bury a traitor who was never born.', availability: 'first_play', revealIds: ['R32', 'R35'] }
];

export const CHAPTER_ONE_TRANSITIONS: readonly NarrativeTransitionRecord[] = [
  { id: 'TR-C1-01', mode: 'standard', placement: 'orders', title: 'The Accord', text: 'Two traditions brought two Witness Wheels to Mont-Rouge. The French wheel opened its eyes. The Swiss wheel was never meant to.', revealIds: ['R01', 'R02', 'R06'] },
  { id: 'TR-C1-02', mode: 'standard', placement: 'after_war_1', title: 'Sealed Swiss Correction', text: 'From Matthias von Greyerz: “Marcel has omitted 11 minutes, one unsigned folio, and the fact that I asked him to wait.”', revealIds: ['R08', 'R12'] },
  { id: 'TR-C1-03', mode: 'standard', placement: 'after_war_2', title: 'Belgian Field Note · Unrequested · Rind-Stained', text: '“Both accounts are honest. This is not the comfort you think it is.”', revealIds: ['R32', 'R35'] },
  { id: 'TR-C1-04', mode: 'standard', placement: 'campaign_complete', title: 'Campaign Dispatch', text: "Mont-Rouge remains unresolved. Each negotiator names the other's next act as the first betrayal. Bastien has submitted a drawing of a field inside a wheel.", revealIds: ['R09', 'R12', 'R34'] }
];

export const CHAPTER_ONE_DOSSIERS: readonly CommanderDossierRecord[] = [
  { id: 'DOS-MAR-01', commanderId: 'quartermaster', unlock: { mode: 'standard', completedWars: 0 }, section: 'Overview', text: 'French master affineur and appointed negotiator. Reputation: exacting cellar steward, formidable reserve planner, and defender of French provenance.', evidence: 'documented', revealIds: ['R01', 'R02', 'R03'], source: { id: 'S02', label: 'What is an affineur?', url: 'https://www.gruyere-france.fr/notre-histoire/' }, relationship: 'new' },
  { id: 'DOS-MAR-02', commanderId: 'quartermaster', unlock: { mode: 'standard', completedWars: 1 }, section: 'Mont-Rouge Record', text: 'Co-authored the Mont-Rouge Accord with Matthias von Greyerz. French accounts state that von Greyerz suspended ratification after the Swiss Witness Wheel opened unexpectedly. De Brie characterized the suspension as a withdrawal of good faith.', evidence: 'attributed interpretation', revealIds: ['R05', 'R06', 'R07', 'R08', 'R09'], source: { id: 'S01', label: 'Gruyère history', url: 'https://www.gruyere.com/en/le-gruyere-aop/the-history' }, relationship: 'new' },
  { id: 'DOS-MAT-01', commanderId: 'analyst', unlock: { mode: 'standard', completedWars: 1 }, section: 'Overview', text: 'Swiss master cheesemaker and standards analyst. Reputation: procedural precision, severe tolerances, and unusual willingness to publish an unfavorable measurement.', evidence: 'documented', revealIds: ['R01', 'R02', 'R03', 'R04'], source: { id: 'S04', label: 'Swiss Gruyère characteristics', url: 'https://www.gruyere.com/en/le-gruyere-aop/characteristics' }, relationship: 'new' },
  { id: 'DOS-MAT-02', commanderId: 'analyst', unlock: { mode: 'standard', completedWars: 2 }, section: 'Mont-Rouge Record', text: 'Supervised the Swiss Witness Wheel. When openings appeared at ratification, requested suspension pending inquiry. Swiss accounts describe the request as procedure; French accounts describe it as withdrawal.', evidence: 'attributed interpretation', revealIds: ['R07', 'R08', 'R09', 'R12'], source: { id: 'S03', label: 'French Gruyère opening standard', url: 'https://inao.gouv.fr/produit/gruyere-4500' }, relationship: 'new' },
  { id: 'DOS-BAS-01', commanderId: 'attritionist', unlock: { mode: 'standard', completedWars: 2 }, section: 'Overview', text: 'Occupation: Tyromancer. Affiliation: none reliably established. Military office: none. Reliability: poor. Predictive record: disturbingly good.', evidence: 'public record', revealIds: [], source: { id: 'S14', label: 'Historical tyromancy', url: 'https://fr.wikisource.org/wiki/L%E2%80%99Encyclop%C3%A9die/1re_%C3%A9dition/TIROMANCIE' }, relationship: 'new' },
  { id: 'DOS-BAS-02', commanderId: 'attritionist', unlock: { mode: 'standard', completedWars: 3 }, section: 'Archived Statement', text: '“The blind wheel opened seven eyes. Four men closed eight.” Recorded: before ratification. Contemporary meaning: unknown.', evidence: 'prophetic metaphor', revealIds: ['R31'], relationship: 'new' }
];
