import {
  AuthoredDialogueRecord,
  CommanderDossierRecord,
  NarrativeTransitionRecord
} from '../core/models/narrative.model';

export const CHAPTER_TWO_DIALOGUE: readonly AuthoredDialogueRecord[] = [
  // War 1 — Sir Edmund Gloucester
  { id: 'C2W1-EDM-01', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'introduction', text: 'Matthias asked for time. Time, in diplomacy, is what one requests when hoping the other fellow misplaces his nerve.', availability: 'first_play', revealIds: ['R10'] },
  { id: 'C2W1-EDM-02', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'context', text: 'I advised Marcel to proceed. An Accord starving in a drawer is only stationery with excellent breeding.', availability: 'first_play', revealIds: ['R10', 'R11', 'R16'] },
  { id: 'C2W1-EDM-03', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'special_clash', text: 'A Two against an Ace? Splendid. The rules have developed a sense of occasion.', availability: 'any' },
  { id: 'C2W1-EDM-04', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'narrow_clash', text: 'One rank short. Practically a recommendation.', availability: 'any' },
  { id: 'C2W1-EDM-05', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'rescue', text: 'There we are. A reserve is merely courage kept in a smaller bottle.', availability: 'replay' },
  { id: 'C2W1-EDM-06', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'failed_rescue', text: 'Bit awkward, that. Still, hesitation would have told a worse story.', availability: 'any' },
  { id: 'C2W1-EDM-07', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'battle_ace_lost', text: 'The grand card took the short route to posterity.', availability: 'any' },
  { id: 'C2W1-EDM-08', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'battle_two_lost', text: 'There goes the quiet little answer to a very loud Ace.', availability: 'any' },
  { id: 'C2W1-EDM-09', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'deep_battle', text: 'Another layer? Right, then. One cannot stop halfway down a hill with dignity.', availability: 'replay' },
  { id: 'C2W1-EDM-10', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'large_battle_loss', text: 'That was most of the winter in one enthusiastic afternoon.', availability: 'replay', revealIds: ['R16'] },
  { id: 'C2W1-EDM-11', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'concession', text: 'Not this hand. Even appetite benefits from cutlery.', availability: 'any' },
  { id: 'C2W1-EDM-12', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'desperate_rescue', text: 'Last card in the purse. Best not spend it timidly.', availability: 'any' },
  { id: 'C2W1-EDM-13', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'contextual', text: 'Go on, then. What does the cheese say? Something with cavalry, if possible.', availability: 'first_play' },
  { id: 'C2W1-EDM-14', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'contextual', text: 'Lorenzo sees one shutter close and orders a census of siege ladders. Exhausting chap.', availability: 'replay' },
  { id: 'C2W1-EDM-15', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'result', text: 'Well played. If the result were certain beforehand, we should have called it accounting.', availability: 'any' },
  { id: 'C2W1-EDM-16', commanderId: 'gambler', mode: 'limited_reserves', warIndex: 1, event: 'resolution', text: 'Yes, I put the word “bluff” in the room. A useful word. Got Marcel moving, didn’t it?', availability: 'first_play', revealIds: ['R10', 'R27'] },

  // War 2 — Lorenzo di Taleggio
  { id: 'C2W2-LOR-01', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'introduction', text: 'Today one sealed wagon. Tomorrow the pass. The day after? Madonna mia, Marcel names the mountain after himself.', availability: 'first_play', revealIds: ['R13', 'R14', 'R15'] },
  { id: 'C2W2-LOR-02', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'context', text: 'I told Matthias what France could gain if we waited. A warning is not a lie because the fire has not reached your room.', availability: 'first_play', revealIds: ['R13', 'R16'] },
  { id: 'C2W2-LOR-03', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'special_clash', text: 'The smallest unit enters through the grandest defense. You see? There is always a pass.', availability: 'any' },
  { id: 'C2W2-LOR-04', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'narrow_clash', text: 'One rank today. Tomorrow two. By Friday your King applies for French citizenship.', availability: 'replay' },
  { id: 'C2W2-LOR-05', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'rescue', text: 'Bene. Reinforce the hinge before it becomes a gate.', availability: 'any' },
  { id: 'C2W2-LOR-06', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'failed_rescue', text: 'We strengthened the door and lost the house. This is suboptimal.', availability: 'any' },
  { id: 'C2W2-LOR-07', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'battle_ace_lost', text: 'The center falls. Inform every pass before rumor arrives wearing a French hat.', availability: 'replay' },
  { id: 'C2W2-LOR-08', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'battle_two_lost', text: 'Our smallest scout is gone. Every Ace just grew taller.', availability: 'any' },
  { id: 'C2W2-LOR-09', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'deep_battle', text: 'Another act! The orchestra has ammunition and no conductor.', availability: 'any' },
  { id: 'C2W2-LOR-10', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'large_battle_loss', text: 'Ten cards. That is not a loss; it is a trade delegation that never comes home.', availability: 'replay', revealIds: ['R15', 'R16'] },
  { id: 'C2W2-LOR-11', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'concession', text: 'We yield the square to hold the road. Strategy is geography with better tailoring.', availability: 'any' },
  { id: 'C2W2-LOR-12', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'desperate_rescue', text: 'No road behind us. Then every card advances!', availability: 'any' },
  { id: 'C2W2-LOR-13', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'contextual', text: 'Edmund calls a threat a wager, as if changing the noun makes the casualty sporting.', availability: 'replay' },
  { id: 'C2W2-LOR-14', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'contextual', text: 'Matthias calculates danger. I merely ensure he does not calculate it too late.', availability: 'first_play' },
  { id: 'C2W2-LOR-15', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'result', text: 'A result is a border drawn by cards. We will inspect it for weaknesses.', availability: 'any' },
  { id: 'C2W2-LOR-16', commanderId: 'cornered-general', mode: 'limited_reserves', warIndex: 2, event: 'resolution', text: 'I recommended restriction before French control became a fact. I listed consequences. Matthias supplied the decision.', availability: 'first_play', revealIds: ['R13', 'R14', 'R15'] },

  // War 3 — Marcel de Brie
  { id: 'C2W3-MAR-01', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'introduction', text: 'I signed because an Accord left to starve is merely expensive paper. Yes, monsieur. I signed without Matthias.', availability: 'first_play', revealIds: ['R11', 'R16'] },
  { id: 'C2W3-MAR-02', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'context', text: 'Then came the restricted pass, the seized wheels, and winter inventory conducted by bayonet. Diplomacy had acquired a rind.', availability: 'first_play', revealIds: ['R14', 'R15', 'R16'] },
  { id: 'C2W3-MAR-03', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'special_clash', text: 'The humblest card preserves one excellent exception. I respect a narrow specification.', availability: 'any' },
  { id: 'C2W3-MAR-04', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'narrow_clash', text: 'One rank saved is one rank not replaced. Stewardship begins in small margins.', availability: 'any' },
  { id: 'C2W3-MAR-05', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'rescue', text: 'One reserve spent. Count the remaining shelves before you applaud.', availability: 'replay' },
  { id: 'C2W3-MAR-06', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'failed_rescue', text: 'A reserve consumed, two cards spoiled, and winter unimpressed.', availability: 'replay' },
  { id: 'C2W3-MAR-07', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'battle_ace_lost', text: 'There are losses one records in ink and losses that stain through the ledger.', availability: 'any' },
  { id: 'C2W3-MAR-08', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'battle_two_lost', text: 'Small does not mean expendable. Only fools and kings confuse the terms.', availability: 'any' },
  { id: 'C2W3-MAR-09', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'deep_battle', text: 'We have spent tomorrow’s shelf on today’s deadlock.', availability: 'replay' },
  { id: 'C2W3-MAR-10', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'large_battle_loss', text: 'That was not a clash. That was a cellar becoming an empty room.', availability: 'replay' },
  { id: 'C2W3-MAR-11', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'concession', text: 'Let it pass. A commander who preserves nothing commands an inventory of ghosts.', availability: 'any' },
  { id: 'C2W3-MAR-12', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'desperate_rescue', text: 'Spend it. There is no virtue in presenting winter with a sealed reserve and no army.', availability: 'replay' },
  { id: 'C2W3-MAR-13', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'contextual', text: 'Edmund advised action. I enjoyed the advice. The signature, however, is mine.', availability: 'first_play', revealIds: ['R10', 'R11'] },
  { id: 'C2W3-MAR-14', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'contextual', text: 'Matthias once waited fourteen months for a rind to settle. I could not give an Accord fourteen more minutes.', availability: 'replay', revealIds: ['R03', 'R04'] },
  { id: 'C2W3-MAR-15', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'result', text: 'The ledger closes on this War. The stores, regrettably, do not refill with the ink.', availability: 'replay' },
  { id: 'C2W3-MAR-16', commanderId: 'quartermaster', mode: 'limited_reserves', warIndex: 3, event: 'resolution', text: 'I ordered escorts to reopen the route. Protection, not invasion. But when they met the cordon, the distinction did not stop the first blade.', availability: 'first_play', revealIds: ['R17', 'R18'] }
];

export const CHAPTER_TWO_TRANSITIONS: readonly NarrativeTransitionRecord[] = [
  { id: 'TR-C2-01', mode: 'limited_reserves', placement: 'orders', title: 'The Closing Passes', text: 'Five reserves. Three Wars. Winter does not return what command spends.', revealIds: ['R16'] },
  { id: 'TR-C2-02', mode: 'limited_reserves', placement: 'after_war_1', title: 'Intercepted Italian Dispatch', text: 'Lorenzo: “The Englishman calls uncertainty a wager. A charming word for making another nation pay the stake.”', revealIds: ['CB08'] },
  { id: 'TR-C2-03', mode: 'limited_reserves', placement: 'after_war_2', title: 'French Route Ledger', text: 'One pass restricted. Seven wagons held. Marcel has ordered escorts for the next convoy and insists this is preservation, not escalation.', revealIds: ['R14', 'R15', 'R17'] },
  { id: 'TR-C2-04', mode: 'limited_reserves', placement: 'campaign_complete', title: 'Campaign Resolution', text: 'The convoy met the cordon before dawn. By noon, both sides possessed blood enough to call every earlier fear a fact.', revealIds: ['R18', 'R19'] }
];

export const CHAPTER_TWO_DOSSIERS: readonly CommanderDossierRecord[] = [
  { id: 'DOS-EDM-01', commanderId: 'gambler', unlock: { mode: 'limited_reserves', completedWars: 0 }, section: 'Overview', text: 'English artisan-adventurer and irregular campaign adviser. Public reputation: dry humor, excellent nerve, and a troubling belief that uncertain odds improve with momentum.', evidence: 'documented', revealIds: [], source: { id: 'S12', label: "Cooper's Hill cheese-rolling", url: 'https://www.gloucestershire.gov.uk/archives/learning-for-all/online-exhibitions/here-we-are-now-entertain-us/' }, relationship: 'new' },
  { id: 'DOS-EDM-02', commanderId: 'gambler', unlock: { mode: 'limited_reserves', completedWars: 1 }, section: 'Known Associations', text: 'Long-standing confidant of Marcel de Brie. Present correspondence records Gloucester using the word “bluff” for the Swiss suspension and recommending immediate French action. Gloucester describes this as support.', evidence: 'documented', revealIds: ['R10', 'R11'], relationship: 'new' },
  { id: 'DOS-LOR-01', commanderId: 'cornered-general', unlock: { mode: 'limited_reserves', completedWars: 1 }, section: 'Overview', text: 'Italian Alpine merchant-prince and cheesemaker. Adviser on passes, markets, and strategic exposure. Reputation: notices tomorrow’s threat early—sometimes before tomorrow has agreed to it.', evidence: 'documented', revealIds: [], source: { id: 'S07', label: 'The geopolitician from Brig', url: 'https://blog.nationalmuseum.ch/en/2023/09/the-geopolitician-from-brig/' }, relationship: 'new' },
  { id: 'DOS-LOR-02', commanderId: 'cornered-general', unlock: { mode: 'limited_reserves', completedWars: 2 }, section: 'Known Associations', text: 'Adviser to Matthias von Greyerz during the route crisis. His memoranda list plausible effects of unilateral French recognition: lost leverage, redirected trade, and eventual control of disputed passes.', evidence: 'attributed interpretation', revealIds: ['R13', 'R14', 'R15', 'R16'], source: { id: 'S08', label: 'Old Alpine trading route revived', url: 'https://www.swissinfo.ch/eng/archive-banking-fintech/old-alpine-trading-route-revived/995202' }, relationship: 'new' },
  { id: 'DOS-MAR-03', commanderId: 'quartermaster', unlock: { mode: 'limited_reserves', completedWars: 3 }, section: 'Campaign Notes', text: 'De Brie proceeded under the negotiated framework without Swiss assent. French escorts later moved to reopen or secure a restricted route. De Brie maintains that delay would have killed the Accord; the record establishes that he chose to act.', evidence: 'documented', revealIds: ['R11', 'R14', 'R15', 'R16', 'R17'], source: { id: 'S07', label: 'Alpine pass geopolitics', url: 'https://blog.nationalmuseum.ch/en/2023/09/the-geopolitician-from-brig/' }, relationship: 'supplement' },
  { id: 'DOS-BAS-03', commanderId: 'attritionist', unlock: { mode: 'limited_reserves', completedWars: 3 }, section: 'Archived Statement', text: 'Original statement preserved. Period annotation: several observers took “eyes” to mean rival inspection standards. Gloucester requested “another one, preferably with cavalry.”', evidence: 'attributed interpretation', revealIds: ['R31'], source: { id: 'S03', label: 'French Gruyère opening standard', url: 'https://inao.gouv.fr/produit/gruyere-4500' }, relationship: 'annotate', relatedRecordId: 'DOS-BAS-02' }
];
