import {
  AuthoredDialogueRecord,
  CommanderDossierRecord,
  NarrativeTransitionRecord
} from '../core/models/narrative.model';

export const CHAPTER_THREE_DIALOGUE: readonly AuthoredDialogueRecord[] = [
  // War 1 — Matthias von Greyerz
  { id: 'C3W1-MAT-01', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'introduction', text: 'Three copies of the steward’s deposition disagree. Two carry his signature. One misspells his name.', availability: 'first_play', revealIds: ['R20'] },
  { id: 'C3W1-MAT-02', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'context', text: 'I began this review to isolate sabotage. Instead, I have isolated the word “sabotage” from every demonstrated mechanism.', availability: 'first_play', revealIds: ['R21', 'R25'] },
  { id: 'C3W1-MAT-03', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'special_clash', text: 'An exception occurred in full view. Note how little intention the fact contains.', availability: 'replay' },
  { id: 'C3W1-MAT-04', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'narrow_clash', text: 'One rank. Fog does not alter the visible interval.', availability: 'any' },
  { id: 'C3W1-MAT-05', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'rescue', text: 'The visible candidate was sufficient. I will not invent data for the rest.', availability: 'any' },
  { id: 'C3W1-MAT-06', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'failed_rescue', text: 'The model failed. No—correction. The outcome differed from the model.', availability: 'replay' },
  { id: 'C3W1-MAT-07', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'battle_ace_lost', text: 'Ace lost. The sealed record will not make it less lost.', availability: 'replay' },
  { id: 'C3W1-MAT-08', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'battle_two_lost', text: 'The specialist is gone. What remains unknown is not therefore favorable.', availability: 'any' },
  { id: 'C3W1-MAT-09', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'deep_battle', text: 'At depth three, certainty decreases faster than the card count.', availability: 'replay' },
  { id: 'C3W1-MAT-10', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'large_battle_loss', text: 'The seal conceals identities. It does not conceal the size of the absence.', availability: 'replay' },
  { id: 'C3W1-MAT-11', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'concession', text: 'Insufficient public basis. We concede without manufacturing one.', availability: 'any' },
  { id: 'C3W1-MAT-12', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'desperate_rescue', text: 'The threshold is visible. Commitment is justified by position, not prophecy.', availability: 'replay' },
  { id: 'C3W1-MAT-13', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'contextual', text: 'I said the record was exact. It is. It is exact in three incompatible directions.', availability: 'first_play', revealIds: ['R20'] },
  { id: 'C3W1-MAT-14', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'contextual', text: 'Bastien’s statements remain inadmissible. They have also become inconveniently prior.', availability: 'first_play', revealIds: ['R31'] },
  { id: 'C3W1-MAT-15', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'result', text: 'Record the War. Do not ask it to prove more than it contains.', availability: 'any' },
  { id: 'C3W1-MAT-16', commanderId: 'analyst', mode: 'fog_of_war', warIndex: 1, event: 'resolution', text: 'The record does not establish what I have spent years saying it establishes.', availability: 'first_play', revealIds: ['R21', 'R29'] },

  // War 2 — Marcel de Brie
  { id: 'C3W2-MAR-01', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'introduction', text: 'The grand histories preserve every insult. The cellar ledger preserves straw, traps, repairs, and one unpaid broom. Guess which nobody read.', availability: 'first_play', revealIds: ['R22', 'R23', 'R24'] },
  { id: 'C3W2-MAR-02', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'context', text: 'I possessed Matthias’s timing, his silence, and my humiliation. I called the bundle intent.', availability: 'first_play', revealIds: ['R30'] },
  { id: 'C3W2-MAR-03', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'special_clash', text: 'A small rule overturns a grand expectation. Mais—expectation was never evidence.', availability: 'replay' },
  { id: 'C3W2-MAR-04', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'narrow_clash', text: 'One rank still matters when the rest of the ledger is sealed.', availability: 'any' },
  { id: 'C3W2-MAR-05', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'rescue', text: 'Preserve what is visible. Do not pretend to inventory the fog.', availability: 'any' },
  { id: 'C3W2-MAR-06', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'failed_rescue', text: 'We spent two certainties and received one excellent correction.', availability: 'replay' },
  { id: 'C3W2-MAR-07', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'battle_ace_lost', text: 'Seal the name if you must. The empty place in the cellar remains exact.', availability: 'replay' },
  { id: 'C3W2-MAR-08', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'battle_two_lost', text: 'The modest card leaves. Every surviving Ace becomes less modest.', availability: 'any' },
  { id: 'C3W2-MAR-09', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'deep_battle', text: 'We descend through records the way we descend through Battles: blind, committed, and carrying too much.', availability: 'replay' },
  { id: 'C3W2-MAR-10', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'large_battle_loss', text: 'So much gone at once, and still the archive will argue about the order.', availability: 'replay', revealIds: ['R19', 'R20'] },
  { id: 'C3W2-MAR-11', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'concession', text: 'No. Uncertainty is not permission to squander stock.', availability: 'any' },
  { id: 'C3W2-MAR-12', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'desperate_rescue', text: 'Open the reserve. Doubt is useful; extinction is less so.', availability: 'any' },
  { id: 'C3W2-MAR-13', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'contextual', text: 'Matthias would have catalogued the broom. I mocked him for such things. This is becoming tiresome.', availability: 'first_play' },
  { id: 'C3W2-MAR-14', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'contextual', text: 'A vermin notice is not a confession. A straw invoice is not a culprit. They are merely records we preferred not to notice.', availability: 'replay', revealIds: ['R23', 'R24'] },
  { id: 'C3W2-MAR-15', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'result', text: 'The fog lifts from this War. I wish history were equally obedient.', availability: 'replay' },
  { id: 'C3W2-MAR-16', commanderId: 'quartermaster', mode: 'fog_of_war', warIndex: 2, event: 'resolution', text: 'I never proved what Matthias intended. I proved what he did, then matured the rest in anger.', availability: 'first_play', revealIds: ['R30'] },

  // War 3 — Bastien de Herve
  { id: 'C3W3-BAS-01', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'introduction', text: 'You have opened the archive. Shall we open the wheel again?', availability: 'first_play', revealIds: ['R31', 'R36'] },
  { id: 'C3W3-BAS-02', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'context', text: 'There is no knife in the wheel. Men sharpened one from the absence.', availability: 'first_play', revealIds: ['R21', 'R35'] },
  { id: 'C3W3-BAS-03', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'special_clash', text: 'The smallest guest takes no chair, yet the general obeys.', availability: 'replay', revealIds: ['R33'] },
  { id: 'C3W3-BAS-04', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'narrow_clash', text: 'One step. Large enough for an army, too small for certainty.', availability: 'any' },
  { id: 'C3W3-BAS-05', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'rescue', text: 'The second card was already waiting in the whey.', availability: 'any' },
  { id: 'C3W3-BAS-06', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'failed_rescue', text: 'The rind promised an arrival. It did not promise success.', availability: 'any' },
  { id: 'C3W3-BAS-07', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'battle_ace_lost', text: 'Great heads fall loudly. Tiny causes prefer cellars.', availability: 'replay', revealIds: ['R33'] },
  { id: 'C3W3-BAS-08', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'battle_two_lost', text: 'The little appointment is complete. Close the enormous book.', availability: 'any' },
  { id: 'C3W3-BAS-09', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'deep_battle', text: 'Cave beneath cave; stem within stem; breath inside both. Now you are listening.', availability: 'replay', revealIds: ['R26'] },
  { id: 'C3W3-BAS-10', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'large_battle_loss', text: 'A field ground smaller than sight can still feed a war.', availability: 'replay', revealIds: ['R26', 'R33'] },
  { id: 'C3W3-BAS-11', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'concession', text: 'Let the visible card go. The invisible future is expensive.', availability: 'any' },
  { id: 'C3W3-BAS-12', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'desperate_rescue', text: 'The line is rind-thin. Press here.', availability: 'any' },
  { id: 'C3W3-BAS-13', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'contextual', text: 'The precise man has requested my exact nonsense. We are both making progress.', availability: 'first_play', revealIds: ['R31'] },
  { id: 'C3W3-BAS-14', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'contextual', text: 'The first casualty had no suit, no rank, no grave. You have found its empty uniform.', availability: 'first_play', revealIds: ['R36'] },
  { id: 'C3W3-BAS-15', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'result', text: 'The seal opens. The bones speak. As warned, they disagree.', availability: 'replay' },
  { id: 'C3W3-BAS-16', commanderId: 'attritionist', mode: 'fog_of_war', warIndex: 3, event: 'resolution', text: 'The traitor remains absent. At last, you have begun to notice him.', availability: 'first_play', revealIds: ['R35', 'R37'] }
];

export const CHAPTER_THREE_TRANSITIONS: readonly NarrativeTransitionRecord[] = [
  { id: 'TR-C3-01', mode: 'fog_of_war', placement: 'orders', title: 'The Blind Wheel', text: 'The Boneyard will be sealed while each War is active. Mont-Rouge’s record has been sealed by certainty for much longer.', revealIds: ['R20'] },
  { id: 'TR-C3-02', mode: 'fog_of_war', placement: 'after_war_1', title: 'Archive Transfer', text: 'Matthias has released the rejected folios: cellar invoices, straw tallies, vermin notices, and three mutually incompatible witness statements. Marcel has asked why nobody read them.', revealIds: ['R20', 'R22', 'R23', 'R24'] },
  { id: 'TR-C3-03', mode: 'fog_of_war', placement: 'after_war_2', title: 'Swiss Request', text: 'Matthias: “Ask the Belgian to repeat the one about the blind wheel. Precisely as he said it.”', revealIds: ['R31'] },
  { id: 'TR-C3-04', mode: 'fog_of_war', placement: 'campaign_complete', title: 'Campaign Resolution', text: 'No saboteur appears in the surviving record. The absence is not proof of innocence. It is, however, where the old certainty used to stand.', revealIds: ['R21', 'R37'] }
];

export const CHAPTER_THREE_DOSSIERS: readonly CommanderDossierRecord[] = [
  { id: 'DOS-MAT-03', commanderId: 'analyst', unlock: { mode: 'fog_of_war', completedWars: 1 }, section: 'Mont-Rouge Record', text: 'Inquiry status amended: testimony conflicts, chain-of-custody records are incomplete, and no surviving inquiry demonstrates a method of sabotage. Von Greyerz has withdrawn several earlier claims from the category “established.”', evidence: 'documented', revealIds: ['R20', 'R21', 'R25'], source: { id: 'S10', label: 'Factors affecting eye development', url: 'https://ira.agroscope.ch/en-US/Page/Einzelpublikation/Download?einzelpublikationId=17389' }, relationship: 'annotate', relatedRecordId: 'DOS-MAT-02' },
  { id: 'DOS-MAR-04', commanderId: 'quartermaster', unlock: { mode: 'fog_of_war', completedWars: 2 }, section: 'Mont-Rouge Record', text: 'Evidentiary note: surviving material establishes the suspension, the unilateral action, and de Brie’s humiliation. It does not establish that von Greyerz intended to abandon either man or Accord. Rejected dairy folios are catalogued separately.', evidence: 'documented', revealIds: ['R20', 'R22', 'R30'], relationship: 'annotate', relatedRecordId: 'DOS-MAR-02' },
  { id: 'DOS-EDM-03', commanderId: 'gambler', unlock: { mode: 'fog_of_war', completedWars: 2 }, section: 'Mont-Rouge Record', text: 'Archival note: multiple drafts intensify from “delay” to “bluff” to “call it.” The progression supports deliberate goading more strongly than Gloucester’s later summaries do.', evidence: 'documented', revealIds: ['R27'], relationship: 'annotate', relatedRecordId: 'DOS-EDM-02' },
  { id: 'DOS-LOR-03', commanderId: 'cornered-general', unlock: { mode: 'fog_of_war', completedWars: 2 }, section: 'Mont-Rouge Record', text: 'Comparative note: successive memoranda preserve the same possibilities while shortening their projected timelines. No new French evidence accompanies the increased urgency.', evidence: 'documented', revealIds: ['R13', 'R28'], relationship: 'annotate', relatedRecordId: 'DOS-LOR-02' },
  { id: 'DOS-BAS-04', commanderId: 'attritionist', unlock: { mode: 'fog_of_war', completedWars: 3 }, section: 'Archived Statement', text: 'Original statement preserved. Archive annotation: the statement predates the Witness Wheel anomaly. “Four men” is consistent with the two negotiators and their principal advisers; no consensus exists regarding the arithmetic.', evidence: 'documented', revealIds: ['R27', 'R28', 'R31'], relationship: 'annotate', relatedRecordId: 'DOS-BAS-02' },
  { id: 'DOS-BAS-05', commanderId: 'attritionist', unlock: { mode: 'fog_of_war', completedWars: 3 }, section: 'Background', text: 'Herve-born rind-seer with no verified partisan service. His Mont-Rouge statements are obscure but internally consistent; no known statement assigns original guilt to France or Switzerland.', evidence: 'documented', revealIds: ['R35', 'R36', 'R37'], source: { id: 'S15', label: 'Cheeses of Wallonia: Herve', url: 'https://visitwallonia.com/en-gb/3/i-love/food-and-drink/specialities/cheese' }, relationship: 'supplement' },
  { id: 'DOS-MAT-04', commanderId: 'analyst', unlock: { mode: 'fog_of_war', completedWars: 3 }, section: 'Known Associations', text: 'Earlier files dismiss Bastien de Herve as inadmissible. A later archive request from von Greyerz asks for one pre-ratification prophecy “precisely as recorded.”', evidence: 'documented', revealIds: ['R31'], source: { id: 'S14', label: 'Historical tyromancy', url: 'https://fr.wikisource.org/wiki/L%E2%80%99Encyclop%C3%A9die/1re_%C3%A9dition/TIROMANCIE' }, relationship: 'supplement' }
];
